# Generated by Django 2.2.6 on 2020-04-21 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ['title', 'ordering'], 'verbose_name': 'Pagina', 'verbose_name_plural': 'Paginas'},
        ),
        migrations.AddField(
            model_name='page',
            name='ordering',
            field=models.SmallIntegerField(default=0, verbose_name='Orden'),
        ),
    ]
